host:
  address: "http://localhost:5000"
  secret: "faputa"
client:
  clientname: "demo"
  printstatus: True
  upload: True
  log: True
  spec-disks:
    enable: False
    mountpoints: ["C:\\","D:\\"]